### ISSUE TITLE
预约时验证码问题

### ISSUE THREAD

**Issue by CGH20171006** [dclemon/-zhihuichangguan#1]
现在登陆需要验证码，请问可以更新一下吗？我对selenium不熟悉，不知道怎么改，但是知道可以使用DDDDOCR库来识别验证码

**Comment by CGH20171006** [comment]
> 

可以加我的Q交流一下1749300329

**Comment by dclemon** [comment]
我最近不需要用这个脚本了因此没有维护计划，如果有验证码的话，调用库识别出验证码后寻找编辑框元素输入就行了，参考我前面的学号密码输入部分

**Comment by CGH20171006** [comment]
验证码问题已经解决，但调试过程中问题似乎还比较多，目前也不清楚是否可以成功运行，不知道可否加一下QQ沟通一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月8日(周三) 晚上11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dclemon/-zhihuichangguan] 预约时验证码问题 (Issue #1)




 
我最近不需要用这个脚本了因此没有维护计划，如果有验证码的话，调用库识别出验证码后寻找编辑框元素输入就行了，参考我前面的学号密码输入部分
